name: RL
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=51_gnu
  - bzip2=1.0.8=h998d150_6
  - ca-certificates=2025.12.2=hd43f75c_0
  - expat=2.7.3=h5b11e9f_4
  - ld_impl_linux-aarch64=2.44=h4e4ac68_2
  - libexpat=2.7.3=h5b11e9f_4
  - libffi=3.4.4=h419075a_1
  - libgcc=15.2.0=hc18542e_7
  - libgcc-ng=15.2.0=h51576c1_7
  - libgomp=15.2.0=hf47c802_7
  - libnsl=2.0.0=h998d150_0
  - libstdcxx=15.2.0=h9538471_7
  - libstdcxx-ng=15.2.0=h719ae8e_7
  - libuuid=1.41.5=h998d150_0
  - libxcb=1.17.0=hf66535e_0
  - libzlib=1.3.1=h998d150_0
  - ncurses=6.5=h419075a_0
  - openssl=3.0.18=h8a9c3cf_0
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=hfd63f10_1
  - python=3.11.14=h81fb49f_0
  - readline=8.3=h886d1d0_0
  - setuptools=80.9.0=py311hd43f75c_0
  - sqlite=3.51.1=hcfd1b6d_0
  - tk=8.6.15=h987d8db_0
  - wheel=0.45.1=py311hd43f75c_0
  - xorg-libx11=1.8.12=hf66535e_1
  - xorg-libxau=1.0.12=hf66535e_0
  - xorg-libxdmcp=1.1.5=hf66535e_0
  - xorg-xorgproto=2024.1=h998d150_1
  - xz=5.6.4=h998d150_1
  - zlib=1.3.1=h998d150_0
  - pip:
      - absl-py==2.3.1
      - accelerate==1.12.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - ansicolors==1.1.8
      - anyio==4.12.1
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==3.0.1
      - async-lru==2.1.0
      - attrs==25.4.0
      - babel==2.17.0
      - beautifulsoup4==4.14.3
      - bitsandbytes==0.49.1
      - bleach==6.3.0
      - certifi==2026.1.4
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - comm==0.2.3
      - cuda-bindings==13.0.3
      - cuda-pathfinder==1.2.2
      - cut-cross-entropy==25.1.1
      - datasets==4.3.0
      - debugpy==1.8.19
      - decorator==5.2.1
      - defusedxml==0.7.1
      - diffusers==0.36.0
      - dill==0.4.0
      - docstring-parser==0.17.0
      - entrypoints==0.4
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filelock==3.20.0
      - fqdn==1.5.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - grpcio==1.76.0
      - h11==0.16.0
      - hf-transfer==0.1.9
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - importlib-metadata==8.7.1
      - iniconfig==2.3.0
      - ipykernel==7.1.0
      - ipython==9.9.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - json5==0.13.0
      - jsonpointer==3.0.0
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-client==8.8.0
      - jupyter-console==6.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.4
      - jupyterlab==4.5.3
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - lark==1.3.1
      - markdown==3.10.1
      - markupsafe==2.1.5
      - matplotlib-inline==0.2.1
      - mistune==3.2.0
      - mpmath==1.3.0
      - msgspec==0.20.0
      - multidict==6.7.0
      - multiprocess==0.70.16
      - nbclient==0.10.4
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.6.1
      - notebook==7.5.2
      - notebook-shim==0.2.4
      - numpy==2.3.5
      - nvidia-cublas==13.1.0.3
      - nvidia-cuda-cupti==13.0.85
      - nvidia-cuda-nvrtc==13.0.88
      - nvidia-cuda-runtime==13.0.96
      - nvidia-cudnn-cu13==9.15.1.9
      - nvidia-cufft==12.0.0.61
      - nvidia-cufile==1.15.1.6
      - nvidia-curand==10.4.0.35
      - nvidia-cusolver==12.0.4.66
      - nvidia-cusparse==12.6.3.3
      - nvidia-cusparselt-cu13==0.8.0
      - nvidia-nccl-cu13==2.28.9
      - nvidia-nvjitlink==13.0.88
      - nvidia-nvshmem-cu13==3.4.5
      - nvidia-nvtx==13.0.85
      - overrides==7.7.0
      - packaging==26.0
      - pandas==3.0.0
      - pandocfilters==1.5.1
      - papermill==2.6.0
      - parso==0.8.5
      - peft==0.18.1
      - pexpect==4.9.0
      - pillow==12.0.0
      - platformdirs==4.5.1
      - pluggy==1.6.0
      - prometheus-client==0.24.1
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - protobuf==6.33.4
      - psutil==7.2.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==23.0.0
      - pycparser==3.0
      - pygments==2.19.2
      - pytest==9.0.2
      - python-dateutil==2.9.0.post0
      - python-json-logger==4.0.0
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - referencing==0.37.0
      - regex==2026.1.15
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.30.0
      - safetensors==0.7.0
      - send2trash==2.1.0
      - sentencepiece==0.2.1
      - six==1.17.0
      - soupsieve==2.8.3
      - stack-data==0.6.3
      - sympy==1.14.0
      - tenacity==9.1.2
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - terminado==0.18.1
      - tinycss2==1.4.0
      - tokenizers==0.22.2
      - torch==2.10.0+cu130
      - torchao==0.15.0
      - torchaudio==2.10.0+cu130
      - torchvision==0.25.0+cu130
      - tornado==6.5.4
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.56.2
      - triton==3.6.0
      - triton-kernels==1.0.0
      - trl==0.22.2
      - typeguard==4.4.4
      - typing-extensions==4.15.0
      - tyro==1.0.5
      - tzdata==2025.3
      - unsloth==2026.1.4
      - unsloth-zoo==2026.1.4
      - uri-template==1.3.0
      - urllib3==2.6.3
      - uv==0.9.26
      - wcwidth==0.3.5
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - werkzeug==3.1.5
      - widgetsnbextension==4.0.15
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
prefix: /home/leonard/miniconda3/envs/RL
